### ISSUE TITLE
"Moderator Required"

### ISSUE THREAD

**Issue by itsjohncs** [itsjohncs/flair-fairy#1]
When I left the bot running for awhile this error (see below) eventually occurred. I feel as if this is most likely due to the session timing out or some other such nonsense.

It crashed the bot, so this should definitely be taken care of. A possible solution may be to simply have a script that constantly restarts the bot when it goes down.

```
Traceback (most recent call last):
  File "reddit-flair-fairy.py", line 153, in <module>
    i.set_flair(map_name(language.lower()))
  File "/usr/lib/python2.6/site-packages/reddit-1.3.8-py2.6.egg/reddit/objects.py", line 613, in set_flair
    return self.subreddit.set_flair(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/reddit-1.3.8-py2.6.egg/reddit/objects.py", line 719, in set_flair
    return self.reddit_session.set_flair(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/reddit-1.3.8-py2.6.egg/reddit/decorators.py", line 204, in login_required_function
    return function(self, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/reddit-1.3.8-py2.6.egg/reddit/decorators.py", line 215, in moderator_required_function
    six.text_type(self.user))
reddit.errors.ModeratorRequired: u'FlairFairy' is not moderator
```

**Comment by itsjohncs** [comment]
Left it on overnight, woke up to this stack trace:

```
Traceback (most recent call last):
  File "reddit-flair-fairy.py", line 124, in <module>
    place_holder = last_checked
  File "/usr/local/lib/python2.7/dist-packages/reddit-1.3.8-py2.7.egg/reddit/__init__.py", line 261, in get_content
    page_data = self.request_json(page_url, url_data=url_data)
  File "/usr/local/lib/python2.7/dist-packages/reddit-1.3.8-py2.7.egg/reddit/decorators.py", line 162, in error_checked_function
    return_value = function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/reddit-1.3.8-py2.7.egg/reddit/__init__.py", line 294, in request_json
    response = self._request(page_url, params, url_data)
  File "/usr/local/lib/python2.7/dist-packages/reddit-1.3.8-py2.7.egg/reddit/__init__.py", line 190, in _request
    url_data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/reddit-1.3.8-py2.7.egg/reddit/decorators.py", line 53, in __call__
    **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/reddit-1.3.8-py2.7.egg/reddit/decorators.py", line 136, in __call__
    return self.function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/reddit-1.3.8-py2.7.egg/reddit/helpers.py", line 99, in _request
    return response.read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
socket.timeout: timed out
```

THe moderator required error one seems to be getting triggered immediately whenever I try to use FlairFairy as the user for the bot, which is strange because FlairFairy is indeed a moderator, and can set flair. I'll need to look into this more.

**Comment by itsjohncs** [comment]
Fixed
